SOURCE_URL = 'https://www.easynepalityping.com/useful-newari-phrases'

UNIT_METADATA_BY_LEVEL = {
    'easy': [
        {
            'unit_key': 'greetings',
            'unit_title': 'Greetings',
            'usage_note': 'Use these in everyday greetings and polite responses.',
            'keywords': ['hello', 'thank you', 'please', 'yes', 'no', 'good morning', 'good evening', 'good night', 'how are you'],
        },
        {
            'unit_key': 'pronouns',
            'unit_title': 'Pronouns',
            'usage_note': 'These are core pronouns used in most beginner conversations.',
            'keywords': [' i', 'you', 'and you'],
        },
        {
            'unit_key': 'numbers',
            'unit_title': 'Numbers',
            'usage_note': 'Number words are essential for money, time, and shopping.',
            'keywords': ['one', 'two', 'three', 'four', 'five', 'ten'],
        },
        {
            'unit_key': 'shopping',
            'unit_title': 'Shopping',
            'usage_note': 'Practice these when asking cost, bags, and basic market terms.',
            'keywords': ['how much', 'bag', 'money', 'price'],
        },
    ],
    'intermediate': [
        {
            'unit_key': 'introductions',
            'unit_title': 'Introductions',
            'usage_note': 'Introduce yourself and ask personal basics naturally.',
            'keywords': ['name', 'from', 'how old', 'student', 'live here'],
        },
        {
            'unit_key': 'shopping',
            'unit_title': 'Shopping',
            'usage_note': 'Use these lines for bargaining, receipts, and discounts.',
            'keywords': ['supermarket', 'souvenirs', 'price', 'receipt', 'expensive', 'discount', 'money back'],
        },
        {
            'unit_key': 'time',
            'unit_title': 'Time',
            'usage_note': 'Time vocabulary helps you discuss dates and schedules.',
            'keywords': ['today', 'tomorrow', 'yesterday', 'now', 'twenty', 'fifty', 'one hundred', 'one thousand'],
        },
    ],
    'hard': [
        {
            'unit_key': 'travel',
            'unit_title': 'Travel',
            'usage_note': 'Use this set for transport, tickets, and route directions.',
            'keywords': ['ticket', 'address', 'airport', 'meter'],
        },
        {
            'unit_key': 'time',
            'unit_title': 'Time',
            'usage_note': 'These forms are useful for asking exact time and durations.',
            'keywords': ['what time', 'at what time', 'week', 'century'],
        },
        {
            'unit_key': 'shopping',
            'unit_title': 'Shopping',
            'usage_note': 'Advanced marketplace language for payments and negotiation.',
            'keywords': ['lower the price', 'credit', 'debit', 'more', 'less'],
        },
    ],
}


def infer_unit_metadata(level, english_text):
    text = f" {str(english_text or '').lower()} "
    units = UNIT_METADATA_BY_LEVEL.get(level, [])

    for index, unit in enumerate(units, start=1):
        if any(keyword in text for keyword in unit['keywords']):
            return {
                'unit_key': unit['unit_key'],
                'unit_title': unit['unit_title'],
                'sort_order': index,
                'usage_note': unit['usage_note'],
            }

    fallback = units[0] if units else {
        'unit_key': 'core',
        'unit_title': 'Core Phrases',
        'usage_note': 'Foundational phrases for daily communication.',
    }
    return {
        'unit_key': fallback['unit_key'],
        'unit_title': fallback['unit_title'],
        'sort_order': 1,
        'usage_note': fallback['usage_note'],
    }

LESSON_SEED_DATA = [
    # EASY - greetings and core basics
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Hello', 'newari_text': 'ज्वजलपा।', 'romanized_text': 'jvajalapa.'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Thank you', 'newari_text': 'सुभाय्।', 'romanized_text': 'subhay.'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Please', 'newari_text': 'बिन्ति।', 'romanized_text': 'binti.'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Yes', 'newari_text': 'ख।', 'romanized_text': 'kha.'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'No', 'newari_text': 'मज्यु।', 'romanized_text': 'majyu.'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Good morning', 'newari_text': 'भिं सुथ।', 'romanized_text': 'bhin suth.'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Good evening', 'newari_text': 'भि सनिल।', 'romanized_text': 'bhi sanil.'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Good night', 'newari_text': 'भिं चा।', 'romanized_text': 'bhin cha.'},
    {'level': 'easy', 'item_type': 'sentence', 'english_text': 'How are you?', 'newari_text': 'म्हं फु ला?', 'romanized_text': 'mhan phu la?'},
    {'level': 'easy', 'item_type': 'sentence', 'english_text': 'I am fine. And you?', 'newari_text': 'जि त ठिक जु। अले छि?', 'romanized_text': 'ji ta thik ju. ale chhi?'},

    # EASY - pronouns and numbers
    {'level': 'easy', 'item_type': 'word', 'english_text': 'I', 'newari_text': 'जिं', 'romanized_text': 'jin'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'You', 'newari_text': 'छित', 'romanized_text': 'chhit'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'One', 'newari_text': '१ - छगू', 'romanized_text': '1 - chhagu'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Two', 'newari_text': '२ - निगू', 'romanized_text': '2 - nigu'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Three', 'newari_text': '३ - स्वंगू', 'romanized_text': '3 - swangu'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Four', 'newari_text': '४ - प्यंगू', 'romanized_text': '4 - pyangu'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Five', 'newari_text': '५ - न्यागू', 'romanized_text': '5 - nyagu'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Ten', 'newari_text': '१० - दस', 'romanized_text': '10 - das'},

    # EASY - shopping starter phrases
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Money', 'newari_text': 'ध्यबा', 'romanized_text': 'dhyaba'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Price', 'newari_text': 'भाः', 'romanized_text': 'bhah'},
    {'level': 'easy', 'item_type': 'sentence', 'english_text': 'How much is it?', 'newari_text': 'थ्व गुलि खः ?', 'romanized_text': 'thwa guli khah?'},
    {'level': 'easy', 'item_type': 'sentence', 'english_text': 'Could I have a bag, please?', 'newari_text': 'जिकेय् म्हिचा छपु बियादी फै ला ?', 'romanized_text': 'jikey mhicha chhapu biyadi phai la?'},
    {'level': 'easy', 'item_type': 'sentence', 'english_text': 'I do not need a bag, thanks.', 'newari_text': 'जितः झोला म्वाः, सुभाय् ।', 'romanized_text': 'jitah jhola mwah, subhay.'},

    # INTERMEDIATE - introductions and daily interactions
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'What is your name?', 'newari_text': 'छङु ना छु ख?', 'romanized_text': 'chhangu na chhu kha?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'Where are you going?', 'newari_text': 'छ गन वनेत्यना ?', 'romanized_text': 'chha gan vanetyana?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'What are you doing?', 'newari_text': 'छु याना चोव्ना?', 'romanized_text': 'chhu yana chovna?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'Where are you from?', 'newari_text': 'छी गना ना झा यू?', 'romanized_text': 'chhi gana na jha yu?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'I am from India.', 'newari_text': 'जि भारतयाम्ह खः ।', 'romanized_text': 'ji bharatayamh khah.'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'How old are you?', 'newari_text': 'छी गुली बर्स?', 'romanized_text': 'chhi guli bars?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'I am a student.', 'newari_text': 'जि छम्ह ब्वनामि खः ।', 'romanized_text': 'ji chhamh bwanami khah.'},

    # INTERMEDIATE - market and practical phrases
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'Where is a supermarket?', 'newari_text': 'सुपरमार्केट गन दु ?', 'romanized_text': 'supermarket gan du?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'Can you write down the price?', 'newari_text': 'छिं भाः च्वयादी फै ला ?', 'romanized_text': 'chhin bhah chwayadi phai la?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'Could I have a receipt, please?', 'newari_text': 'जिके रसिद बियादी फै ला ?', 'romanized_text': 'jike rasid biyadi phai la?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'That is too expensive.', 'newari_text': 'व तसकं थिके ।', 'romanized_text': 'wa tasakang thike.'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'Can you give me a discount?', 'newari_text': 'छिं जितः छ्यापं बियादी फै ला ?', 'romanized_text': 'chhin jitah chhyapan biyadi phai la?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'I would like my money back, please.', 'newari_text': 'जितः जिगु ध्यबा लित बी मास्ति वः ।', 'romanized_text': 'jitah jigu dhyaba lit bi masti wah.'},

    # INTERMEDIATE - time and numbers
    {'level': 'intermediate', 'item_type': 'word', 'english_text': 'Today', 'newari_text': 'थौं', 'romanized_text': 'thaun'},
    {'level': 'intermediate', 'item_type': 'word', 'english_text': 'Tomorrow', 'newari_text': 'कने', 'romanized_text': 'kane'},
    {'level': 'intermediate', 'item_type': 'word', 'english_text': 'Yesterday', 'newari_text': 'म्हिग', 'romanized_text': 'mhig'},
    {'level': 'intermediate', 'item_type': 'word', 'english_text': 'Now', 'newari_text': 'आ', 'romanized_text': 'aa'},
    {'level': 'intermediate', 'item_type': 'word', 'english_text': 'Fifty', 'newari_text': '५० - नेर्का', 'romanized_text': '50 - nerka'},
    {'level': 'intermediate', 'item_type': 'word', 'english_text': 'One hundred', 'newari_text': '१०० - सच्छि', 'romanized_text': '100 - sachchi'},
    {'level': 'intermediate', 'item_type': 'word', 'english_text': 'One thousand', 'newari_text': '१,००० - दोछी', 'romanized_text': '1000 - dochi'},

    # HARD - travel and advanced context
    {'level': 'hard', 'item_type': 'sentence', 'english_text': 'Can you lower the price?', 'newari_text': 'छिं भाः क्वकाये फै ला ?', 'romanized_text': 'chhin bhah kwakaye phai la?'},
    {'level': 'hard', 'item_type': 'sentence', 'english_text': 'Do you accept credit/debit cards?', 'newari_text': 'छिं क्रेडिट / डेबिट कार्ड स्वीकार याना ला ?', 'romanized_text': 'chhin credit debit card swikar yana la?'},
    {'level': 'hard', 'item_type': 'sentence', 'english_text': 'Where can I buy a ticket?', 'newari_text': 'जिं टिकट गन न्याये फै ?', 'romanized_text': 'jin ticket gan nyaye phai?'},
    {'level': 'hard', 'item_type': 'sentence', 'english_text': 'Please take me to this address.', 'newari_text': 'जितः थुगु थासय् यंकादिसँ ।', 'romanized_text': 'jitah thugu thasay yankadisan.'},
    {'level': 'hard', 'item_type': 'sentence', 'english_text': 'Please turn on the meter.', 'newari_text': 'मिटर चायेकादिसँ ।', 'romanized_text': 'meter chayekadisan.'},
    {'level': 'hard', 'item_type': 'sentence', 'english_text': 'How long will it take to get to the airport?', 'newari_text': 'एयरपोर्ट थ्यंकेत गुलि ई काइ ?', 'romanized_text': 'airport thyanket guli i kai?'},
    {'level': 'hard', 'item_type': 'sentence', 'english_text': 'What time is it?', 'newari_text': 'आः गुलि ई जुल ?', 'romanized_text': 'ah guli i jul?'},
    {'level': 'hard', 'item_type': 'sentence', 'english_text': 'At what time?', 'newari_text': 'गुगु इलय् ?', 'romanized_text': 'gugu ilay?'},
    {'level': 'hard', 'item_type': 'word', 'english_text': 'Century', 'newari_text': 'शताब्दी', 'romanized_text': 'shatabdi'},
    {'level': 'hard', 'item_type': 'word', 'english_text': 'Within a Week', 'newari_text': 'छवाःया दुने', 'romanized_text': 'chhavahya dune'},
    {'level': 'hard', 'item_type': 'word', 'english_text': 'More', 'newari_text': 'योक्को', 'romanized_text': 'yokko'},
    {'level': 'hard', 'item_type': 'word', 'english_text': 'Less', 'newari_text': 'मगागु', 'romanized_text': 'magagu'},
]

QUIZ_SEED_DATA = [
    # ─── EASY ───────────────────────────────────────────────────────────────
    {
        'level': 'easy',
        'linked_english_text': 'Hello',
        'question_text': 'What is the Newari word for Hello?',
        'option_a': 'ज्वजलपा।',
        'option_b': 'सुभाय्।',
        'option_c': 'भिं चा।',
        'option_d': 'बिन्ति।',
        'correct_option': 'A',
        'explanation': 'Hello in Newari is ज्वजलपा।',
    },
    {
        'level': 'easy',
        'linked_english_text': 'Price',
        'question_text': 'Choose the Newari word for Price.',
        'option_a': 'ध्यबा',
        'option_b': 'भाः',
        'option_c': 'थौं',
        'option_d': 'म्हिग',
        'correct_option': 'B',
        'explanation': 'Price is भाः.',
    },
    {
        'level': 'easy',
        'linked_english_text': 'Five',
        'question_text': 'What is the Newari number for Five?',
        'option_a': 'न्यागू',
        'option_b': 'निगू',
        'option_c': 'दस',
        'option_d': 'स्वंगू',
        'correct_option': 'A',
        'explanation': 'Five in the lesson is न्यागू.',
    },
    {
        'level': 'easy',
        'linked_english_text': 'Please',
        'question_text': 'What is the Newari word for "Please"?',
        'option_a': 'ज्वजलपा।',
        'option_b': 'मज्यु।',
        'option_c': 'बिन्ति।',
        'option_d': 'सुभाय्।',
        'correct_option': 'C',
        'explanation': 'Please in Newari is बिन्ति।',
    },
    {
        'level': 'easy',
        'linked_english_text': 'No',
        'question_text': 'What does मज्यु। mean?',
        'option_a': 'Yes',
        'option_b': 'Hello',
        'option_c': 'Please',
        'option_d': 'No',
        'correct_option': 'D',
        'explanation': 'मज्यु। means No in Newari.',
    },
    {
        'level': 'easy',
        'linked_english_text': 'Yes',
        'question_text': 'What is the Newari word for "Yes"?',
        'option_a': 'ख।',
        'option_b': 'मज्यु।',
        'option_c': 'बिन्ति।',
        'option_d': 'भिं चा।',
        'correct_option': 'A',
        'explanation': 'Yes in Newari is ख।',
    },
    {
        'level': 'easy',
        'linked_english_text': 'Good morning',
        'question_text': 'What does भिं सुथ। mean?',
        'option_a': 'Good night',
        'option_b': 'Good evening',
        'option_c': 'Good morning',
        'option_d': 'Hello',
        'correct_option': 'C',
        'explanation': 'भिं सुथ। means Good morning.',
    },
    {
        'level': 'easy',
        'linked_english_text': 'I',
        'question_text': 'What is the Newari word for "I"?',
        'option_a': 'छित',
        'option_b': 'जिं',
        'option_c': 'ख।',
        'option_d': 'आ',
        'correct_option': 'B',
        'explanation': 'I in Newari is जिं.',
    },
    {
        'level': 'easy',
        'linked_english_text': 'How much is it?',
        'question_text': 'What does थ्व गुलि खः ? mean?',
        'option_a': 'Where are you going?',
        'option_b': 'How are you?',
        'option_c': 'How much is it?',
        'option_d': 'What is your name?',
        'correct_option': 'C',
        'explanation': 'थ्व गुलि खः ? means How much is it?',
    },
    {
        'level': 'easy',
        'linked_english_text': 'Money',
        'question_text': 'Which is the Newari word for "Money"?',
        'option_a': 'भाः',
        'option_b': 'ध्यबा',
        'option_c': 'थौं',
        'option_d': 'म्हिग',
        'correct_option': 'B',
        'explanation': 'Money in Newari is ध्यबा.',
    },
    {
        'level': 'easy',
        'linked_english_text': 'One',
        'question_text': 'What is १ in Newari?',
        'option_a': 'निगू',
        'option_b': 'स्वंगू',
        'option_c': 'छगू',
        'option_d': 'न्यागू',
        'correct_option': 'C',
        'explanation': 'One in Newari is छगू.',
    },

    # ─── INTERMEDIATE ────────────────────────────────────────────────────────
    {
        'level': 'intermediate',
        'linked_english_text': 'Can you give me a discount?',
        'question_text': 'Which sentence asks for a discount?',
        'option_a': 'छिं जित: छ्यापं बियादी फै ला ?',
        'option_b': 'थ्व गुलि खः ?',
        'option_c': 'मिटर चायेकादिसँ ।',
        'option_d': 'गुगु इलय् ?',
        'correct_option': 'A',
        'explanation': 'This sentence means Can you give me a discount?',
    },
    {
        'level': 'intermediate',
        'linked_english_text': 'Could I have a receipt, please?',
        'question_text': 'What is the meaning of जिके रसिद बियादी फै ला ?',
        'option_a': 'Please write the price',
        'option_b': 'Could I have a receipt, please?',
        'option_c': 'I would like money back',
        'option_d': 'Where is supermarket?',
        'correct_option': 'B',
        'explanation': 'It is a receipt request sentence.',
    },
    {
        'level': 'intermediate',
        'linked_english_text': 'One hundred',
        'question_text': 'Choose the Newari form of One hundred.',
        'option_a': '५० - न्यासः',
        'option_b': '१० - दस',
        'option_c': '१०० - सच्छि',
        'option_d': '१,००० - छद्वः',
        'correct_option': 'C',
        'explanation': 'One hundred is १०० - सच्छि.',
    },
    {
        'level': 'intermediate',
        'linked_english_text': 'That is too expensive.',
        'question_text': 'Which sentence means "That is too expensive"?',
        'option_a': 'व तसकं थिके ।',
        'option_b': 'छी गुली बर्स?',
        'option_c': 'छिं भाः च्वयादी फै ला ?',
        'option_d': 'जि भारतयाम्ह खः ।',
        'correct_option': 'A',
        'explanation': 'व तसकं थिके । means too expensive.',
    },
    {
        'level': 'intermediate',
        'linked_english_text': 'What is your name?',
        'question_text': 'What does छङु ना छु ख? mean?',
        'option_a': 'How old are you?',
        'option_b': 'Where are you from?',
        'option_c': 'What is your name?',
        'option_d': 'Do you live here?',
        'correct_option': 'C',
        'explanation': 'छङु ना छु ख? means What is your name?',
    },
    {
        'level': 'intermediate',
        'linked_english_text': 'Today',
        'question_text': 'What is the Newari word for "Today"?',
        'option_a': 'कने',
        'option_b': 'म्हिग',
        'option_c': 'आ',
        'option_d': 'थौं',
        'correct_option': 'D',
        'explanation': 'Today in Newari is थौं.',
    },
    {
        'level': 'intermediate',
        'linked_english_text': 'Tomorrow',
        'question_text': 'What is the Newari word for "Tomorrow"?',
        'option_a': 'थौं',
        'option_b': 'कने',
        'option_c': 'म्हिग',
        'option_d': 'आ',
        'correct_option': 'B',
        'explanation': 'Tomorrow in Newari is कने.',
    },
    {
        'level': 'intermediate',
        'linked_english_text': 'I am a student.',
        'question_text': 'What does जि छम्ह ब्वनामि खः । mean?',
        'option_a': 'I am a teacher.',
        'option_b': 'I am from India.',
        'option_c': 'I am a student.',
        'option_d': 'I am fine.',
        'correct_option': 'C',
        'explanation': 'जि छम्ह ब्वनामि खः । means I am a student.',
    },
    {
        'level': 'intermediate',
        'linked_english_text': 'Fifty',
        'question_text': 'What is ५० in Newari?',
        'option_a': 'नीदँ',
        'option_b': 'सच्छि',
        'option_c': 'नेर्का',
        'option_d': 'दोछी',
        'correct_option': 'C',
        'explanation': 'Fifty in Newari is नेर्का.',
    },
    {
        'level': 'intermediate',
        'linked_english_text': 'Where are you going?',
        'question_text': 'Which sentence means "Where are you going?"?',
        'option_a': 'छ गन वनेत्यना ?',
        'option_b': 'छि थन च्वनादी ला ?',
        'option_c': 'छु याना चोव्ना?',
        'option_d': 'छी गना ना झा यू?',
        'correct_option': 'A',
        'explanation': 'छ गन वनेत्यना ? means Where are you going?',
    },
    {
        'level': 'intermediate',
        'linked_english_text': 'What are you doing?',
        'question_text': 'What does छु याना चोव्ना? mean?',
        'option_a': 'Where are you from?',
        'option_b': 'What are you doing?',
        'option_c': 'How old are you?',
        'option_d': 'Do you live here?',
        'correct_option': 'B',
        'explanation': 'छु याना चोव्ना? means What are you doing?',
    },

    # ─── HARD ────────────────────────────────────────────────────────────────
    {
        'level': 'hard',
        'linked_english_text': 'Please turn on the meter.',
        'question_text': 'What does मिटर चायेकादिसँ । mean?',
        'option_a': 'Turn on AC',
        'option_b': 'Take me to airport',
        'option_c': 'Please turn on the meter',
        'option_d': 'Can I have receipt',
        'correct_option': 'C',
        'explanation': 'It is used for taxi meter request.',
    },
    {
        'level': 'hard',
        'linked_english_text': 'How long will it take to get to the airport?',
        'question_text': 'Choose the sentence for asking travel time to airport.',
        'option_a': 'एयरपोर्ट थ्यंकेत गुलि ई काइ ?',
        'option_b': 'गुगु इलय् ?',
        'option_c': 'आः गुलि ई जुल ?',
        'option_d': 'छवाःया दुने',
        'correct_option': 'A',
        'explanation': 'This asks how long it takes to get to airport.',
    },
    {
        'level': 'hard',
        'linked_english_text': 'Century',
        'question_text': 'Which one means Century?',
        'option_a': 'शताब्दी',
        'option_b': 'मगागु',
        'option_c': 'योक्को',
        'option_d': 'छवाःया दुने',
        'correct_option': 'A',
        'explanation': 'Century in lesson is शताब्दी.',
    },
    {
        'level': 'hard',
        'linked_english_text': 'Within a Week',
        'question_text': 'Within a Week in Newari is:',
        'option_a': 'मगागु',
        'option_b': 'छवाःया दुने',
        'option_c': 'गुगु इलय् ?',
        'option_d': 'व तसकं थिके ।',
        'correct_option': 'B',
        'explanation': 'Within a Week is छवाःया दुने.',
    },
    {
        'level': 'hard',
        'linked_english_text': 'What time is it?',
        'question_text': 'What does आः गुलि ई जुल ? mean?',
        'option_a': 'At what time?',
        'option_b': 'What time is it?',
        'option_c': 'How long will it take?',
        'option_d': 'When are you coming?',
        'correct_option': 'B',
        'explanation': 'आः गुलि ई जुल ? means What time is it?',
    },
    {
        'level': 'hard',
        'linked_english_text': 'At what time?',
        'question_text': 'What does गुगु इलय् ? mean?',
        'option_a': 'What time is it?',
        'option_b': 'How long will it take?',
        'option_c': 'At what time?',
        'option_d': 'When did you arrive?',
        'correct_option': 'C',
        'explanation': 'गुगु इलय् ? means At what time?',
    },
    {
        'level': 'hard',
        'linked_english_text': 'Can you lower the price?',
        'question_text': 'Which sentence means "Can you lower the price?"?',
        'option_a': 'छिं भाः च्वयादी फै ला ?',
        'option_b': 'छिं भाः क्वकाये फै ला ?',
        'option_c': 'व तसकं थिके ।',
        'option_d': 'जिं छन्त ५ तका बी ।',
        'correct_option': 'B',
        'explanation': 'छिं भाः क्वकाये फै ला ? means Can you lower the price?',
    },
    {
        'level': 'hard',
        'linked_english_text': 'Please take me to this address.',
        'question_text': 'What does जितः थुगु थासय् यंकादिसँ । mean?',
        'option_a': 'Please turn on the meter',
        'option_b': 'Take me to this address',
        'option_c': 'Where can I buy a ticket?',
        'option_d': 'Do you accept cards?',
        'correct_option': 'B',
        'explanation': 'It means Please take me to this address.',
    },
    {
        'level': 'hard',
        'linked_english_text': 'More',
        'question_text': 'What is the Newari word for "More"?',
        'option_a': 'मगागु',
        'option_b': 'शताब्दी',
        'option_c': 'योक्को',
        'option_d': 'छवाःया दुने',
        'correct_option': 'C',
        'explanation': 'More in Newari is योक्को.',
    },
    {
        'level': 'hard',
        'linked_english_text': 'Less',
        'question_text': 'What is the Newari word for "Less"?',
        'option_a': 'योक्को',
        'option_b': 'मगागु',
        'option_c': 'शताब्दी',
        'option_d': 'छवाःया दुने',
        'correct_option': 'B',
        'explanation': 'Less in Newari is मगागु.',
    },
]
