SOURCE_URL = 'https://www.easynepalityping.com/useful-newari-phrases'

LESSON_SEED_DATA = [
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Hello', 'newari_text': 'ज्वजलपा।', 'romanized_text': 'jvajalapa.'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Thank you', 'newari_text': 'सुभाय्।', 'romanized_text': 'subhaay.'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Please', 'newari_text': 'बिन्ति।', 'romanized_text': 'binti.'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Yes', 'newari_text': 'ख।', 'romanized_text': 'kh.'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'No', 'newari_text': 'मज्यु।', 'romanized_text': 'majyu.'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Good morning', 'newari_text': 'भिं सुथ।', 'romanized_text': 'bhin suth.'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Good evening', 'newari_text': 'भि सनिल।', 'romanized_text': 'bhi sanil.'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Good night', 'newari_text': 'भिं चा।', 'romanized_text': 'bhin cha.'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'I', 'newari_text': 'जिं', 'romanized_text': 'jin'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'You', 'newari_text': 'छित', 'romanized_text': 'chhit'},
    {'level': 'easy', 'item_type': 'sentence', 'english_text': 'How are you?', 'newari_text': 'म्हं फु ला?', 'romanized_text': 'mhan phu la?'},
    {'level': 'easy', 'item_type': 'sentence', 'english_text': 'I am fine. And you?', 'newari_text': 'जि त ठिक जु। अले छि?', 'romanized_text': 'ji ta thik ju. ale chhi?'},
    {'level': 'easy', 'item_type': 'sentence', 'english_text': 'How much is it?', 'newari_text': 'थ्व गुलि खः ?', 'romanized_text': 'thv guli khah ?'},
    {'level': 'easy', 'item_type': 'sentence', 'english_text': 'Could I have a bag, please?', 'newari_text': 'जिकेय् म्हिचा छपु बियादी फै ला ?', 'romanized_text': 'jikey mhicha chhapu biyaadee phai la ?'},
    {'level': 'easy', 'item_type': 'sentence', 'english_text': 'I do not need a bag, thanks.', 'newari_text': 'जित: झोला म्वाः, सुभाय् ।', 'romanized_text': 'jit: jhola mvaah, subhaay .'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Money', 'newari_text': 'ध्यबा', 'romanized_text': 'dhyaba'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Price', 'newari_text': 'भाः', 'romanized_text': 'bhaah'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'One', 'newari_text': '१ - छगू', 'romanized_text': '1 - chhagoo'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Two', 'newari_text': '२ - निगू', 'romanized_text': '2 - nigoo'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Three', 'newari_text': '३ - स्वंगू', 'romanized_text': '3 - svangoo'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Four', 'newari_text': '४ - प्यंगू', 'romanized_text': '4 - pyangoo'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Five', 'newari_text': '५ - न्यागू', 'romanized_text': '5 - nyaagoo'},
    {'level': 'easy', 'item_type': 'word', 'english_text': 'Ten', 'newari_text': '१० - दस', 'romanized_text': '10 - das'},

    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'What is your name?', 'newari_text': 'छङु ना छु ख?', 'romanized_text': 'chhanu na chhu kh?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'Do you live here?', 'newari_text': 'छि थन च्वनादी ला ?', 'romanized_text': 'chhi than chvanaadee la ?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'Where are you going?', 'newari_text': 'छ गन वनेत्यना ?', 'romanized_text': 'chh gan vanetyana ?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'What are you doing?', 'newari_text': 'छु याना चोव्ना?', 'romanized_text': 'chhu yaana chovna?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'Where are you from?', 'newari_text': 'छी गना ना झा यू?', 'romanized_text': 'chhee gana na jha yoo?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'I am from India.', 'newari_text': 'जि भारतयाम्ह खः ।', 'romanized_text': 'ji bhaaratayaamh khah .'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'How old are you?', 'newari_text': 'छी गुली बर्स?', 'romanized_text': 'chhee gulee bars?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'I am a student.', 'newari_text': 'जि छम्ह ब्वनामि खः ।', 'romanized_text': 'ji chhamh bvanaami khah .'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'Where is a supermarket?', 'newari_text': 'सुपरमार्केट गन दु ?', 'romanized_text': 'suparamaarket gan du ?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'Where can I buy souvenirs?', 'newari_text': 'जिं लुमन्ति चिं गन न्याये फै ?', 'romanized_text': 'jin lumanti chin gan nyaaye phai ?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'Can you write down the price?', 'newari_text': 'छिं भाः च्वयादी फै ला ?', 'romanized_text': 'chhin bhaah chvayaadee phai la ?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'Could I have a receipt, please?', 'newari_text': 'जिके रसिद बियादी फै ला ?', 'romanized_text': 'jike rasid biyaadee phai la ?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'That is too expensive.', 'newari_text': 'व तसकं थिके ।', 'romanized_text': 'va tasakan thike .'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'I will give you 5 Rupees.', 'newari_text': 'जिं छन्त ५ तका बी ।', 'romanized_text': 'jin chhant 5 taka bee .'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'Can you give me a discount?', 'newari_text': 'छिं जित: छ्यापं बियादी फै ला ?', 'romanized_text': 'chhin jit: chhyaapan biyaadee phai la ?'},
    {'level': 'intermediate', 'item_type': 'sentence', 'english_text': 'I would like my money back, please.', 'newari_text': 'जितः जिगु ध्यबा लित बी मास्ति वः ।', 'romanized_text': 'jitah jigu dhyaba lit bee maasti vah .'},
    {'level': 'intermediate', 'item_type': 'word', 'english_text': 'Today', 'newari_text': 'थौं', 'romanized_text': 'thaun'},
    {'level': 'intermediate', 'item_type': 'word', 'english_text': 'Tomorrow', 'newari_text': 'कने', 'romanized_text': 'kane'},
    {'level': 'intermediate', 'item_type': 'word', 'english_text': 'Yesterday', 'newari_text': 'म्हिग', 'romanized_text': 'mhig'},
    {'level': 'intermediate', 'item_type': 'word', 'english_text': 'Now', 'newari_text': 'आ', 'romanized_text': 'aa'},
    {'level': 'intermediate', 'item_type': 'word', 'english_text': 'Twenty', 'newari_text': '२० - नीदँ', 'romanized_text': '20 - needan'},
    {'level': 'intermediate', 'item_type': 'word', 'english_text': 'Fifty', 'newari_text': '५० - नेर्का', 'romanized_text': '50 - nerka'},
    {'level': 'intermediate', 'item_type': 'word', 'english_text': 'One hundred', 'newari_text': '१०० - सच्छि', 'romanized_text': '100 - sachchhi'},
    {'level': 'intermediate', 'item_type': 'word', 'english_text': 'One thousand', 'newari_text': '१,००० - दोछी', 'romanized_text': '1,000 - dochi'},

    {'level': 'hard', 'item_type': 'sentence', 'english_text': 'Can you lower the price?', 'newari_text': 'छिं भाः क्वकाये फै ला ?', 'romanized_text': 'chhin bhaah kvakaaye phai la ?'},
    {'level': 'hard', 'item_type': 'sentence', 'english_text': 'Do you accept credit/debit cards?', 'newari_text': 'छिं क्रेडिट / डेबिट कार्ड स्वीकार याना ला ?', 'romanized_text': 'chhin kredit / debit kaard sveekaar yaana la ?'},
    {'level': 'hard', 'item_type': 'sentence', 'english_text': 'Where can I buy a ticket?', 'newari_text': 'जिं टिकट गन न्याये फै ?', 'romanized_text': 'jin tikat gan nyaaye phai ?'},
    {'level': 'hard', 'item_type': 'sentence', 'english_text': 'Please take me to this address.', 'newari_text': 'जितः थुगु थासय् यंकादिसँ ।', 'romanized_text': 'jitah thugu thaasay yankaadisan .'},
    {'level': 'hard', 'item_type': 'sentence', 'english_text': 'Please turn on the meter.', 'newari_text': 'मिटर चायेकादिसँ ।', 'romanized_text': 'mitar chaayekaadisan .'},
    {'level': 'hard', 'item_type': 'sentence', 'english_text': 'How long will it take to get to the airport?', 'newari_text': 'एयरपोर्ट थ्यंकेत गुलि ई काइ ?', 'romanized_text': 'eyaraport thyanket guli ee kai ?'},
    {'level': 'hard', 'item_type': 'sentence', 'english_text': 'What time is it?', 'newari_text': 'आः गुलि ई जुल ?', 'romanized_text': 'aah guli ee jul ?'},
    {'level': 'hard', 'item_type': 'sentence', 'english_text': 'At what time?', 'newari_text': 'गुगु इलय् ?', 'romanized_text': 'gugu ilay ?'},
    {'level': 'hard', 'item_type': 'word', 'english_text': 'Century', 'newari_text': 'शताब्दी', 'romanized_text': 'shataabdee'},
    {'level': 'hard', 'item_type': 'word', 'english_text': 'Within a Week', 'newari_text': 'छवाःया दुने', 'romanized_text': 'chhavaahya dune'},
    {'level': 'hard', 'item_type': 'word', 'english_text': 'More', 'newari_text': 'योक्को', 'romanized_text': 'yokko'},
    {'level': 'hard', 'item_type': 'word', 'english_text': 'Less', 'newari_text': 'मगागु', 'romanized_text': 'magaagu'},
]

QUIZ_SEED_DATA = [
    {
        'level': 'easy',
        'question_text': 'What is the Newari word for Hello?',
        'option_a': 'ज्वजलपा।',
        'option_b': 'सुभाय्।',
        'option_c': 'भिं चा।',
        'option_d': 'बिन्ति।',
        'correct_option': 'A',
        'explanation': 'Hello in Newari is ज्वजलपा।',
    },
    {
        'level': 'easy',
        'question_text': 'What does सुभाय्। mean in English?',
        'option_a': 'Please',
        'option_b': 'Thank you',
        'option_c': 'Good night',
        'option_d': 'Sorry',
        'correct_option': 'B',
        'explanation': 'सुभाय्। is used for Thank you.',
    },
    {
        'level': 'easy',
        'question_text': 'Choose the Newari word for Price.',
        'option_a': 'ध्यबा',
        'option_b': 'भाः',
        'option_c': 'थौं',
        'option_d': 'म्हिग',
        'correct_option': 'B',
        'explanation': 'Price is भाः.',
    },
    {
        'level': 'easy',
        'question_text': 'What is the Newari number for Five?',
        'option_a': '५ - न्यागू',
        'option_b': '२ - निगू',
        'option_c': '१० - दस',
        'option_d': '३ - स्वंगू',
        'correct_option': 'A',
        'explanation': 'Five in the lesson is ५ - न्यागू.',
    },
    {
        'level': 'intermediate',
        'question_text': 'Which sentence asks for discount?',
        'option_a': 'छिं जित: छ्यापं बियादी फै ला ?',
        'option_b': 'थ्व गुलि खः ?',
        'option_c': 'मिटर चायेकादिसँ ।',
        'option_d': 'गुगु इलय् ?',
        'correct_option': 'A',
        'explanation': 'This sentence means Can you give me a discount?',
    },
    {
        'level': 'intermediate',
        'question_text': 'What is the meaning of जिके रसिद बियादी फै ला ? ',
        'option_a': 'Please write the price',
        'option_b': 'Could I have a receipt, please?',
        'option_c': 'I would like money back',
        'option_d': 'Where is supermarket?',
        'correct_option': 'B',
        'explanation': 'It is a receipt request sentence.',
    },
    {
        'level': 'intermediate',
        'question_text': 'Choose the Newari form of One hundred.',
        'option_a': '५० - न्यासः',
        'option_b': '१० - दस',
        'option_c': '१०० - सच्छि',
        'option_d': '१,००० - छद्वः',
        'correct_option': 'C',
        'explanation': 'One hundred is १०० - सच्छि.',
    },
    {
        'level': 'intermediate',
        'question_text': 'Which sentence means That is too expensive?',
        'option_a': 'व तसकं थिके ।',
        'option_b': 'छी गुली बर्स?',
        'option_c': 'छिं भाः च्वयादी फै ला ?',
        'option_d': 'जि भारतयाम्ह खः ।',
        'correct_option': 'A',
        'explanation': 'व तसकं थिके । means too expensive.',
    },
    {
        'level': 'hard',
        'question_text': 'What does मिटर चायेकादिसँ । mean?',
        'option_a': 'Turn on AC',
        'option_b': 'Take me to airport',
        'option_c': 'Please turn on the meter',
        'option_d': 'Can I have receipt',
        'correct_option': 'C',
        'explanation': 'It is used for taxi meter request.',
    },
    {
        'level': 'hard',
        'question_text': 'Choose the sentence for asking travel time to airport.',
        'option_a': 'एयरपोर्ट थ्यंकेत गुलि ई काइ ?',
        'option_b': 'गुगु इलय् ?',
        'option_c': 'आः गुलि ई जुल ?',
        'option_d': 'छवाःया दुने',
        'correct_option': 'A',
        'explanation': 'This asks how long it takes to get to airport.',
    },
    {
        'level': 'hard',
        'question_text': 'Which one means Century?',
        'option_a': 'शताब्दी',
        'option_b': 'मगागु',
        'option_c': 'योक्को',
        'option_d': 'छवाःया दुने',
        'correct_option': 'A',
        'explanation': 'Century in lesson is शताब्दी.',
    },
    {
        'level': 'hard',
        'question_text': 'Within a Week in Newari is:',
        'option_a': 'मगागु',
        'option_b': 'छवाःया दुने',
        'option_c': 'गुगु इलय् ?',
        'option_d': 'व तसकं थिके ।',
        'correct_option': 'B',
        'explanation': 'Within a Week is छवाःया दुने.',
    },
]